//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kramatdjati.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGLAccount
    {
        public int idAccount { get; set; }
        public string AccName { get; set; }
        public int idAccountType { get; set; }
        public bool RetainedEarnings { get; set; }
        public bool Active { get; set; }
        public string AccCode { get; set; }
        public bool AccKas { get; set; }
    
        public virtual tblGLAccountType tblGLAccountType { get; set; }
    }
}
