//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kramatdjati.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGLAccountType
    {
        public tblGLAccountType()
        {
            this.tblGLAccounts = new HashSet<tblGLAccount>();
        }
    
        public int idAccountType { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<tblGLAccount> tblGLAccounts { get; set; }
    }
}
